version: '3'
services: 

    nginx-proxy:
        container_name: proxyNginx
        image: jwilder/nginx-proxy
        ports:
         - "80:80"
         - "443:443"
        volumes:
         - /var/run/docker.sock:/tmp/docker.sock:ro
         - certs:/etc/nginx/certs:ro
         - confd:/etc/nginx/conf.d
         - vhostd:/etc/nginx/vhost.d
         - html:/usr/share/nginx/html
        labels:
         - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
        


    #  lestencrypte
    letsencrypt:
         image: duch/letsencrypt-nginx-proxy-companion:stable
         restart: always
         volumes:
         - certs:/etc/nginx/certs:rw
         - confd:/etc/nginx/conf.d
         - vhostd:/etc/nginx/vhost.d
         - html:/usr/share/nginx/html
         - /var/run/docker.sock:/var/run/docker.sock:ro        

networks:
    default:
        external:
            name: wordpress
        
volumes:
    certs:
    html:
    vhostd:
    confd:
