
version: '3'
services: 

# CONFIGURATION site 1 test.com
    nginx-web:
        container_name: nginx-web
        image: nginx:1.19.0-alpine
        volumes:
           - $PWD/nginx:/etc/nginx/conf.d
           - $PWD/content:/var/www/html

        environment:
            - VIRTUAL_HOST= web.com #url 
            # - LETSENCRYPT_HOST=desarrolloiot.ml
            # - LETSENCRYPT_EMAIL=andres857@gmail.com
        expose: 
         - "80"
        links:
         - wp-web
        # networks:
        #    - wordpress

    # CONFIGURATION WORDPRESS 
    wp-web: 
        container_name: wp-web
        depends_on:      
         - db
        image: wordpress:php7.2-fpm-alpine
        volumes:      
         - $PWD/content:/var/www/html
        environment:
            WORDPRESS_DB_HOST: db    
            WORDPRESS_DB_NAME: web
            WORDPRESS_DB_USER: desarrollo 
            WORDPRESS_DB_PASSWORD: admin
        links:
         - db
        # networks:
        #    - wordpress
        
# CONFIGURATION DATABASE 
        
    db:
        container_name: db-cobo
        image: mysql:5.7
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        environment:
         - MYSQL_ROOT_PASSWORD=my-secret-pw
         - MYSQL_DATABASE=web
         - MYSQL_USER=desarrollo
         - MYSQL_PASSWORD=admin  
        
            
        volumes:
        - $PWD/db:/var/lib/mysql

        # networks:
        #    - wordpress


networks:
   default:
    external:
        name: wordpress